// flow-typed signature: 26e2254e4f4e84f727cfa6a50b6b6506
// flow-typed version: <<STUB>>/babel-preset-expo_v^4.0.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-expo/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'babel-preset-expo/__tests__/samples/App' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-expo/__tests__/index-test.js' {
  declare module.exports: $Exports<'babel-preset-expo/__tests__/index-test'>;
}
declare module 'babel-preset-expo/__tests__/samples/App.js' {
  declare module.exports: $Exports<'babel-preset-expo/__tests__/samples/App'>;
}
declare module 'babel-preset-expo/index' {
  declare module.exports: $Exports<'babel-preset-expo'>;
}
declare module 'babel-preset-expo/index.js' {
  declare module.exports: $Exports<'babel-preset-expo'>;
}
