// flow-typed signature: 910fb4dc686adfa48d8e7ccba15cd0a4
// flow-typed version: <<STUB>>/node-cleanup_v^2.1.2/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-cleanup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-cleanup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-cleanup/node-cleanup' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/bin/grandchild' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/bin/groupable' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/bin/stackable' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/lib/library' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/multiple' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/nocleanup' {
  declare module.exports: any;
}

declare module 'node-cleanup/tests/single' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-cleanup/node-cleanup.js' {
  declare module.exports: $Exports<'node-cleanup/node-cleanup'>;
}
declare module 'node-cleanup/tests/bin/grandchild.js' {
  declare module.exports: $Exports<'node-cleanup/tests/bin/grandchild'>;
}
declare module 'node-cleanup/tests/bin/groupable.js' {
  declare module.exports: $Exports<'node-cleanup/tests/bin/groupable'>;
}
declare module 'node-cleanup/tests/bin/stackable.js' {
  declare module.exports: $Exports<'node-cleanup/tests/bin/stackable'>;
}
declare module 'node-cleanup/tests/lib/library.js' {
  declare module.exports: $Exports<'node-cleanup/tests/lib/library'>;
}
declare module 'node-cleanup/tests/multiple.js' {
  declare module.exports: $Exports<'node-cleanup/tests/multiple'>;
}
declare module 'node-cleanup/tests/nocleanup.js' {
  declare module.exports: $Exports<'node-cleanup/tests/nocleanup'>;
}
declare module 'node-cleanup/tests/single.js' {
  declare module.exports: $Exports<'node-cleanup/tests/single'>;
}
